# Generated by Django 3.1.7 on 2021-03-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo_list',
            table='todo_board_list',
        ),
    ]
